import 'dart:async';
import 'package:flutter/material.dart';
import '../firebase/firestore_service.dart';
import '../models/post_model.dart';
import '../models/user_model.dart';

class PostProvider extends ChangeNotifier {
  final FirestoreService _firestoreService = FirestoreService();

  List<PostModel> _posts = [];
  List<PostModel> _userPosts = [];
  bool _isLoading = false;

  StreamSubscription<List<PostModel>>? _postsSubscription;
  StreamSubscription<List<PostModel>>? _userPostsSubscription;

  List<PostModel> get posts => _posts;
  List<PostModel> get userPosts => _userPosts;
  bool get isLoading => _isLoading;

  PostProvider() {
    _subscribeToPosts();
  }

  void _setLoading(bool value) {
    _isLoading = value;
    notifyListeners();
  }

  /// Listens to real-time feed updates from Firestore
  void _subscribeToPosts() {
    _postsSubscription?.cancel();
    _postsSubscription = _firestoreService.getPostsStream().listen(
      (updatedPosts) {
        _posts = updatedPosts;
        notifyListeners();
      },
      onError: (e) {
        // Handle errors silently or log
      },
    );
  }

  /// Listens to posts authored by a specific user
  void subscribeToUserPosts(String uid) {
    _userPostsSubscription?.cancel();
    _userPostsSubscription = _firestoreService.getUserPostsStream(uid).listen(
      (updatedUserPosts) {
        _userPosts = updatedUserPosts;
        notifyListeners();
      },
      onError: (e) {
        // Handle errors
      },
    );
  }

  /// Creates a new post without any image attachments
  Future<void> createPost({
    required String content,
    required UserModel currentUser,
  }) async {
    _setLoading(true);
    try {
      final newPost = PostModel(
        id: '', // Generated by Firestore
        authorId: currentUser.uid,
        authorName: currentUser.displayName,
        authorPhotoUrl: currentUser.photoUrl,
        content: content,
        imageUrl: null, // Image posting disabled
        likes: [],
        commentsCount: 0,
        createdAt: DateTime.now(),
      );

      await _firestoreService.createPost(newPost);
    } finally {
      _setLoading(false);
    }
  }

  /// Edits an existing post without any image attachments
  Future<void> editPost({
    required String postId,
    required String content,
    required String userId,
  }) async {
    _setLoading(true);
    try {
      await _firestoreService.updatePost(postId, content: content, imageUrl: null);
    } finally {
      _setLoading(false);
    }
  }

  /// Deletes a post and cleans up associated database nodes
  Future<void> deletePost(String postId) async {
    _setLoading(true);
    try {
      await _firestoreService.deletePost(postId);
    } finally {
      _setLoading(false);
    }
  }

  /// Toggles likes on a post and triggers notifications
  Future<void> toggleLike(String postId, String userId, UserModel currentPoster) async {
    try {
      await _firestoreService.toggleLikePost(postId, userId, currentPoster);
    } catch (e) {
      // Handle error
    }
  }

  @override
  void dispose() {
    _postsSubscription?.cancel();
    _userPostsSubscription?.cancel();
    super.dispose();
  }
}
