// File generated by FlutterFire CLI or defined manually for project setup.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase projects.
///
/// To generate the final production configuration with your credentials, run:
///   `flutterfire configure`
///
/// This will automatically connect your Flutter app to Firebase projects.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macOS - '
          'you can reconfigure this by running the FlutterFire CLI.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for Windows - '
          'you can reconfigure this by running the FlutterFire CLI.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for Linux - '
          'you can reconfigure this by running the FlutterFire CLI.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCiWkRKO2S6TxIBEAMtMxbfhCuArJmr3Pw',
    appId: '1:1060014540798:web:7ec350d5699138c0b7a2af',
    messagingSenderId: '1060014540798',
    projectId: 'campuslink-5206c',
    authDomain: 'campuslink-5206c.firebaseapp.com',
    storageBucket: 'campuslink-5206c.firebasestorage.app',
    measurementId: 'G-G7P4MTEDQ4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCiw3o7oY0-zW2EFoGFSvy4yYju1VCKy3Y',
    appId: '1:1060014540798:android:14edd8a08de9c4dfb7a2af',
    messagingSenderId: '1060014540798',
    projectId: 'campuslink-5206c',
    storageBucket: 'campuslink-5206c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCIHp7YwqBoWRKmU1WZmxdT6iW2LltrS1g',
    appId: '1:1060014540798:ios:5213ebb968359753b7a2af',
    messagingSenderId: '1060014540798',
    projectId: 'campuslink-5206c',
    storageBucket: 'campuslink-5206c.firebasestorage.app',
    iosBundleId: 'com.example.campusLink',
  );

}